---
apiVersion: v1
kind: Pod
metadata:
  name: nacos-consul-adapter
  namespace: study
  labels:
    app: nacos-consul-adapter
    version: v1.0.0
spec:
  containers:
    - name: nacos-consul-adapter
      image: harbor.5g.xuanwu.com:7443/dev/nacos-consul-adapter:v1.0.0
      ports:
        - containerPort: 18501
          hostPort: 18081
      resources:
        limits:
          memory: 50Mi
          cpu: 10m
        requests:
          memory: 10Mi
          cpu: 10m